services:
  proxy:
    image: nginx:stable-alpine
    restart: always
    volumes: 
      - ./nginx:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - example_default
networks:
  example_default:
    external: true
